include ./theme.conf

#STRART_Shift_selection_fix
map ctrl+shift+left no_op
map ctrl+shift+right no_op
map ctrl+shift+home no_op
map ctrl+shift+end no_op
#END_Shift_selection_fix

# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMonoNL Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 11.0
window_padding_width 12 8
enable_audio_bell no
visual_bell_duration 0.0
# END_KITTY_FONTS

background_opacity 0.88
wayland_titlebar_color background
dynamic_background_opacity yes
